const diseases =
{
  drug_reaction: "Allergist",
  allergy: "Allergist",
  hypertension: "Cardiologist",
  heart_attack: "Cardiologist",
  psoriasis: "Dermatologist",
  chicken_pox: "Dermatologist",
  acne: "Dermatologist",
  impetigo: "Dermatologist",
  fungal_infection: "Dermatologist",
  hypothyroidism: "Endocrinologist",
  diabetes: "Endocrinologist",
  hypoglycemia: "Endocrinologist",
  hyperthyroidism: "Endocrinologist",
  gerd: "Gastroenterologist",
  peptic_ulcer_disease: "Gastroenterologist",
  jaundice: "Gastroenterologist",
  dimorphic_hemorrhoids: "Gastroenterologist",
  gastroenteritis: "Gastroenterologist",
  urinary_tract_infection: "Gynecologist",
  chronic_cholestasis: "Hepatologist",
  hepatitis_a: "Hepatologist",
  hepatitis_b: "Hepatologist",
  hepatitis_c: "Hepatologist",
  hepatitis_d: "Hepatologist",
  hepatitis_e: "Hepatologist",
  alcoholic_hepatitis: "Hepatologist",
  malaria: "Internal Medicine",
  dengue: "Internal Medicine",
  migraine: "Neurologist",
  cervical_spondylosis: "Neurologist",
  paralysis_brain_hemorrhage: "Neurologist",
  aids: "Osteopathic",
  paroxysmal_positional_vertigo: "Otolaryngologist",
  common_cold: "Otolaryngologist",
  typhoid: "Pediatrician",
  varicose_veins: "Phlebologist",
  bronchial_asthma: "Pulmonologist",
  pneumonia: "Pulmonologist",
  osteoarthritis: "Rheumatologist",
  arthritis: "Rheumatologist",
  tuberculosis: "Tuberculosis Specialist"
}
  ;

module.exports = {diseases};